export enum AnalyticsEvent {
  // Component
  LIST_COMPONENTS = "LIST_COMPONENTS",
  GET_COMPONENTS = "GET_COMPONENTS",
  GET_COMPONENT_PROPS = "GET_COMPONENT_PROPS",
  GET_COMPONENT_EXAMPLES = "GET_COMPONENT_EXAMPLES",
  // Docs
  LIST_DOCS = "LIST_DOCS",
  GET_DOCS_CONTENT = "GET_DOCS_CONTENT",
  // Themes
  GET_THEMES = "GET_THEMES",
  GET_THEME_VARIABLES = "GET_THEME_VARIABLES",
}

export enum AnalyticsErrorEvent {
  // Component
  LIST_COMPONENTS_ERROR = "LIST_COMPONENTS_ERROR",
  GET_COMPONENTS_ERROR = "GET_COMPONENTS_ERROR",
  GET_COMPONENT_PROPS_ERROR = "GET_COMPONENT_PROPS_ERROR",
  GET_COMPONENT_EXAMPLES_ERROR = "GET_COMPONENT_EXAMPLES_ERROR",
  GET_COMPONENT_EXAMPLES_DEPENDENCIES_WARNING = "GET_COMPONENT_EXAMPLES_DEPENDENCIES_WARNING",
  // Docs
  LIST_DOCS_ERROR = "LIST_DOCS_ERROR",
  GET_DOCS_CONTENT_ERROR = "GET_DOCS_CONTENT_ERROR",
  // Themes
  GET_THEMES_ERROR = "GET_THEMES_ERROR",
  GET_THEME_VARIABLES_ERROR = "GET_THEME_VARIABLES_ERROR",
}

export interface AnalyticsProperties {
  endpoint: string;
  responseTime: number;
  [key: string]: unknown;
}
