export enum AnalyticsEvent {
  // Component
  LIST_COMPONENTS = "LIST_COMPONENTS",
  GET_COMPONENTS = "GET_COMPONENTS",
  GET_COMPONENT_PROPS = "GET_COMPONENT_PROPS",
  GET_COMPONENT_EXAMPLES = "GET_COMPONENT_EXAMPLES",
  GET_COMPONENT_SOURCE = "GET_COMPONENT_SOURCE",
  GET_COMPONENT_STYLES = "GET_COMPONENT_STYLES",
  // Docs
  LIST_DOCS = "LIST_DOCS",
  GET_DOCS_CONTENT = "GET_DOCS_CONTENT",
  // Themes
  GET_THEMES = "GET_THEMES",
  GET_THEME_VARIABLES = "GET_THEME_VARIABLES",
  // Versions
  GET_VERSIONS = "GET_VERSIONS",
}

export enum AnalyticsErrorEvent {
  // Component
  LIST_COMPONENTS_ERROR = "LIST_COMPONENTS_ERROR",
  GET_COMPONENTS_ERROR = "GET_COMPONENTS_ERROR",
  GET_COMPONENT_PROPS_ERROR = "GET_COMPONENT_PROPS_ERROR",
  GET_COMPONENT_EXAMPLES_ERROR = "GET_COMPONENT_EXAMPLES_ERROR",
  GET_COMPONENT_SOURCE_ERROR = "GET_COMPONENT_SOURCE_ERROR",
  GET_COMPONENT_STYLES_ERROR = "GET_COMPONENT_STYLES_ERROR",
  // Docs
  LIST_DOCS_ERROR = "LIST_DOCS_ERROR",
  GET_DOCS_CONTENT_ERROR = "GET_DOCS_CONTENT_ERROR",
  // Themes
  GET_THEMES_ERROR = "GET_THEMES_ERROR",
  GET_THEME_VARIABLES_ERROR = "GET_THEME_VARIABLES_ERROR",
  // Versions
  GET_VERSIONS_ERROR = "GET_VERSIONS_ERROR",
}

export interface AnalyticsProperties {
  endpoint: string;
  responseTime: number;
  [key: string]: unknown;
}
