export enum AnalyticsEvent {
  // Tools
  GET_MIGRATION_GUIDE = "GET_MIGRATION_GUIDE",
  LIST_MIGRATION_GUIDES = "LIST_MIGRATION_GUIDES",
  GET_COMPONENT_GUIDES = "GET_COMPONENT_GUIDES",
  GET_STYLING_MIGRATION_GUIDE = "GET_STYLING_MIGRATION_GUIDE",
  GET_HOOKS_MIGRATION_GUIDE = "GET_HOOKS_MIGRATION_GUIDE",
  // Health
  HEALTH_CHECK = "HEALTH_CHECK",
}

export enum AnalyticsErrorEvent {
  // Tools
  GET_MIGRATION_GUIDE_ERROR = "GET_MIGRATION_GUIDE_ERROR",
  LIST_MIGRATION_GUIDES_ERROR = "LIST_MIGRATION_GUIDES_ERROR",
  GET_COMPONENT_GUIDES_ERROR = "GET_COMPONENT_GUIDES_ERROR",
  GET_STYLING_MIGRATION_GUIDE_ERROR = "GET_STYLING_MIGRATION_GUIDE_ERROR",
  GET_HOOKS_MIGRATION_GUIDE_ERROR = "GET_HOOKS_MIGRATION_GUIDE_ERROR",
  // Health
  HEALTH_CHECK_ERROR = "HEALTH_CHECK_ERROR",
}

export interface AnalyticsProperties {
  endpoint: string;
  responseTime: number;
  [key: string]: unknown;
}
